import type { Metadata } from "next";
import {Space_Grotesk} from "next/font/google";
import "./globals.css";
import Navbar from '@/app/(UI)/Layuot'
const space_Grotesk = Space_Grotesk({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Positivus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={space_Grotesk.className}>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/icon.ico" sizes="any" />
      <body className="p-4 sm:p-7 md:p-8 lg:p-9 xl:p-10">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
